
delete from orders where order_id in (7263,7574,7621);

ALTER TABLE `orders` 
CHANGE `order_date_submit` `order_date_submit` DATETIME NULL, 
CHANGE `order_status` `order_status` CHAR DEFAULT 'n',
CHANGE `arrive` `arrive` DATE NOT NULL, 
CHANGE `address2` `address2` TINYTEXT DEFAULT NULL, 
CHANGE `depart` `depart` DATE NULL, 
CHANGE `phone_day` `phone_day` varchar(20) NULL, 
CHANGE `phone_eve` `phone_eve` varchar(20) NULL, 
CHANGE `phone_fax` `phone_fax` varchar(20) NULL, 
CHANGE `heard_from` `heard_from` tinytext NULL, 
CHANGE `instructions` `instructions` text NULL,
CHANGE `agree_policies` `agree_policies` CHAR(1) NULL,
CHANGE `ip` `ip` varCHAR(15) NULL,
CHANGE `user_agent` `user_agent` TINYTEXT NULL,
CHANGE `cc_exp` `cc_exp` varchar(10) NULL;

alter table resorts change `resortgroup` `active` int default 1;
update resorts set active=1;

DROP TABLE IF EXISTS `countries`;

CREATE TABLE `countries` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `abbrev` varchar(5) DEFAULT NULL,
  `full` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `countries` (`id`, `abbrev`, `full`)
VALUES
	(1,'AF','Afghanistan'),
	(2,'AL','Albania'),
	(3,'DZ','Algeria'),
	(4,'AS','American Samoa'),
	(5,'AD','Andorra'),
	(6,'AO','Angola'),
	(7,'AI','Anguilla'),
	(8,'AQ','Antarctica'),
	(9,'AG','Antigua/Barbuda'),
	(10,'AR','Argentina'),
	(11,'AM','Armenia'),
	(12,'AW','Aruba'),
	(13,'AU','Australia'),
	(14,'AT','Austria'),
	(15,'AZ','Azerbaijan'),
	(16,'BS','Bahamas'),
	(17,'BH','Bahrain'),
	(18,'BD','Bangladesh'),
	(19,'BB','Barbados'),
	(20,'BY','Belarus'),
	(21,'BE','Belgium'),
	(22,'BZ','Belize'),
	(23,'BJ','Benin'),
	(24,'BM','Bermuda'),
	(25,'BT','Bhutan'),
	(26,'BO','Bolivia'),
	(27,'BA','Bosnia'),
	(28,'BW','Botswana'),
	(29,'BV','Bouvet Island'),
	(30,'BR','Brazil'),
	(31,'IO','British Indian Ocean Territory'),
	(32,'WI','British West Indies'),
	(33,'BN','Brunei Darussalam'),
	(34,'BG','Bulgaria'),
	(35,'BF','Burkina Faso'),
	(36,'BU','Burma'),
	(37,'BI','Burundi'),
	(38,'KH','Cambodia'),
	(39,'CM','Cameroon'),
	(40,'CA','Canada'),
	(41,'CV','Cape Verde'),
	(42,'KY','Cayman Islands'),
	(43,'CF','Central Africa'),
	(44,'TD','Chad'),
	(45,'CL','Chile'),
	(46,'CN','China'),
	(47,'CX','Christmas Island'),
	(48,'CC','Cocos (Keeling) Islands'),
	(49,'CO','Colombia'),
	(50,'KM','Comoros'),
	(51,'CG','Congo'),
	(52,'CK','Cook Islands'),
	(53,'CR','Costa Rica'),
	(54,'CI','Cote D\'Ivoire'),
	(55,'HR','Croatia'),
	(56,'CU','Cuba'),
	(57,'CY','Cyprus'),
	(58,'CZ','Czech Republic'),
	(59,'DK','Denmark'),
	(60,'DJ','Djibouti'),
	(61,'DM','Dominica'),
	(62,'DO','Dominican Republic'),
	(63,'TP','East Timor'),
	(64,'EC','Ecuador'),
	(65,'EG','Egypt'),
	(66,'SV','El Salvador'),
	(67,'GB','England'),
	(68,'GQ','Equatorial Guinea'),
	(69,'ER','Eritrea'),
	(70,'EE','Estonia'),
	(71,'ET','Ethiopia'),
	(72,'FO','Faeroe Islands'),
	(73,'FK','Falkland Islands'),
	(74,'FJ','Fiji'),
	(75,'FI','Finland'),
	(76,'FR','France'),
	(77,'PF','French Polynesia'),
	(78,'TF','French Southern Territories'),
	(79,'GA','Gabon'),
	(80,'GM','Gambia'),
	(81,'XA','Gaza'),
	(82,'GE','Georgia'),
	(83,'DE','Germany'),
	(84,'GH','Ghana'),
	(85,'GI','Gibraltar'),
	(86,'GR','Greece'),
	(87,'GL','Greenland'),
	(88,'GD','Grenada'),
	(89,'GP','Guadeloupe'),
	(90,'GU','Guam'),
	(91,'GT','Guatemala'),
	(92,'GF','Guiana'),
	(93,'GN','Guinea'),
	(94,'GW','Guinea-Bissau'),
	(95,'GY','Guyana'),
	(96,'HT','Haiti'),
	(97,'HM','Heard And Mcdonald Islands'),
	(98,'XH','Held Territories'),
	(99,'HN','Honduras'),
	(100,'HK','Hong Kong'),
	(101,'HU','Hungary'),
	(102,'IS','Iceland'),
	(103,'IN','India'),
	(104,'XI','Indian Ocean Islands'),
	(105,'ID','Indonesia'),
	(106,'IR','Iran'),
	(107,'IQ','Iraq'),
	(108,'IE','Ireland'),
	(109,'IL','Israel'),
	(110,'IT','Italy'),
	(111,'JM','Jamaica'),
	(112,'JP','Japan'),
	(113,'JO','Jordan'),
	(114,'KZ','Kazakhstan'),
	(115,'KE','Kenya'),
	(116,'KI','Kiribati'),
	(117,'KR','Korea'),
	(118,'KW','Kuwait'),
	(119,'KG','Kyrgyzstan'),
	(120,'LA','Laos'),
	(121,'LV','Latvia'),
	(122,'LB','Lebanon'),
	(123,'LS','Lesotho'),
	(124,'LR','Liberia'),
	(125,'LY','Libya'),
	(126,'LI','Liechtenstein'),
	(127,'LT','Lithuania'),
	(128,'LU','Luxembourg'),
	(129,'MO','Macau'),
	(130,'MK','Macedonia'),
	(131,'MG','Madagascar'),
	(132,'MW','Malawi'),
	(133,'MY','Malaysia'),
	(134,'MV','Maldives'),
	(135,'ML','Mali'),
	(136,'MT','Malta'),
	(137,'MH','Marshall Islands'),
	(138,'MQ','Martinique'),
	(139,'MR','Mauritania'),
	(140,'MU','Mauritius'),
	(141,'YT','Mayotte'),
	(142,'MX','Mexico'),
	(143,'FM','Micronesia'),
	(144,'MD','Moldova'),
	(145,'MC','Monaco'),
	(146,'MN','Mongolia'),
	(147,'MS','Montserrat'),
	(148,'MA','Morocco'),
	(149,'MZ','Mozambique'),
	(150,'MM','Myanmar'),
	(151,'NA','Namibia'),
	(152,'NR','Nauru'),
	(153,'NP','Nepal'),
	(154,'NL','Netherlands'),
	(155,'AN','Netherlands Antilles'),
	(156,'NC','New Caledonia'),
	(157,'NZ','New Zealand'),
	(158,'NI','Nicaragua'),
	(159,'NE','Niger'),
	(160,'NG','Nigeria'),
	(161,'NU','Niue'),
	(162,'NF','Norfolk Island'),
	(163,'KP','North Korea'),
	(164,'XB','Northern Ireland'),
	(165,'MP','Northern Mariana Islands'),
	(166,'NO','Norway'),
	(167,'OM','Oman'),
	(168,'PK','Pakistan'),
	(169,'PW','Palau'),
	(170,'PA','Panama'),
	(171,'PG','PapuaNew Guinea'),
	(172,'PY','Paraguay'),
	(173,'PE','Peru'),
	(174,'PH','Philippines'),
	(175,'PN','Pitcairn'),
	(176,'PL','Poland'),
	(177,'PT','Portugal'),
	(178,'PR','Puerto Rico'),
	(179,'QA','Qatar'),
	(180,'RE','Reunion'),
	(181,'RO','Romania'),
	(182,'RU','Russia'),
	(183,'RW','Rwanda'),
	(184,'LC','SaintLucia'),
	(185,'SM','San Marino'),
	(186,'ST','Sao Tome And Principe'),
	(187,'SA','Saudi Arabia'),
	(188,'WY','Scotland'),
	(189,'SN','Senegal'),
	(190,'SC','Seychelles'),
	(191,'SL','Sierra Leone'),
	(192,'SG','Singapore'),
	(193,'SK','Slovak Republic'),
	(194,'SI','Slovenia'),
	(195,'SB','Solomon Islands'),
	(196,'SO','Somalia'),
	(197,'ZA','South Africa'),
	(198,'GS','South Georgia'),
	(199,'ES','Spain'),
	(200,'LK','Sri Lanka'),
	(201,'SH','St. Helena'),
	(202,'KN','St. Kitts &amp; Nevis'),
	(203,'PM','St. Pierre'),
	(204,'VC','St. Vincent &amp; The Grendadines'),
	(205,'SD','Sudan'),
	(206,'SR','Suriname'),
	(207,'SJ','Svalbard And Jan Mayen Islands'),
	(208,'SZ','Swaziland'),
	(209,'SE','Sweden'),
	(210,'CH','Switzerland'),
	(211,'SY','Syria'),
	(212,'TW','Taiwan'),
	(213,'TJ','Tajikistan'),
	(214,'TZ','Tanzania'),
	(215,'TH','Thailand'),
	(216,'TG','Togo'),
	(217,'TK','Tokelau'),
	(218,'TO','Tonga'),
	(219,'TT','Trinidad And Tobago'),
	(220,'TN','Tunisia'),
	(221,'TR','Turkey'),
	(222,'TM','Turkmenistan'),
	(223,'TC','Turks And Caicos Islands'),
	(224,'TV','Tuvalu'),
	(225,'UM','U.S. Minor Outlying Islands'),
	(226,'UG','Uganda'),
	(227,'UA','Ukraine'),
	(228,'AE','United Arab Emirates'),
	(229,'UY','Uruguay'),
	(230,'UZ','Uzbekistan'),
	(231,'VU','Vanuatu'),
	(232,'VA','Vatican City State'),
	(233,'VE','Venezuela'),
	(234,'VN','Vietnam'),
	(235,'VG','Virgin Islands (British)'),
	(236,'VI','Virgin Islands (U.S.)'),
	(237,'WX','Wales'),
	(238,'WF','Wallis And Futuna Islands'),
	(239,'EH','Western Sahara'),
	(240,'WS','Western Samoa'),
	(241,'YE','Yemen'),
	(242,'YU','Yugoslavia'),
	(243,'ZR','Zaire'),
	(244,'ZM','Zambia'),
	(245,'ZW','Zimbabwe'),
	(246,'US','United States');



DROP TABLE IF EXISTS `res_notifications`;

CREATE TABLE `res_notifications` (
  `notification_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `notification_name` varchar(50) NOT NULL DEFAULT '',
  `notification_type` char(1) NOT NULL DEFAULT 't',
  `notification_subject` varchar(100) NOT NULL DEFAULT '',
  `notification_content` text NOT NULL,
  PRIMARY KEY (`notification_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


INSERT INTO `res_notifications` (`notification_id`, `notification_name`, `notification_type`, `notification_subject`, `notification_content`)
VALUES
	(1,'Big/All','h','%%resort_name%% Reservation Request Big ALL','<pre>\r\nFirst Name:         %%first_name%%\r\nLast Name:          %%last_name%%\r\nEmail:              %%email%%\r\nDay Phone:          %%phone_day%%\r\nEvening Phone:      %%phone_eve%%\r\nFax:                %%phone_fax%%\r\nAdults:             %%adults%%\r\nKids:               %%kids%%\r\nCondo Type:         %%resort%% - %%condo%%\r\nArrival:            %%arrive%%\r\nDeparture:          %%depart%%\r\nHowHeardOfUs:       %%heard_from%%\r\nCredit Card Number: %%cc_num%%\r\nCC Expiration:      %%cc_exp%%\r\nCC CVC:             %%cc_cvc%%\r\nName On CC:         %%cc_name%%\r\nAddress 1:          %%address1%%\r\nAddress 2:          %%address2%%\r\nCity:               %%city%%\r\nState/Prov:         %%state%%\r\nZip/Postal Code:    %%zip%%\r\nSpec. Instructions: %%instructions%%\r\nRead Policy:        %%agree_policies%%\r\nSubtotal:           %%subtotal%%\r\nTax:                %%tax%%\r\nBooking Fee:        %%booking%%\r\nCleaning Fee:       %%cleaning%%\r\nImpact Fee:         %%impact%%\r\nTotal:              %%total%%\r\nIP Address:         %%ip%%\r\nHTTP User Agent:    %%user_agent%%\r\nDate:               %%now_date%%\r\nTime:               %%now_time%%\r\n</pre>'),
	(2,'Excel Import Data','t','%%resort_name%% Reservation Request Excel','\"first_name\"	\"last_name\"	\"Email\"	\"DayPhone\"	\"EveningPhone\"	\"Fax\"	\"occupants\"	\"occupants_small\"	\"Condo Type\"	\"FirstArrive\"	\"FirstDepart\"	\"HowHeardOfUs\"	\"Comments\"	\"CC Type\"	\"Credit_Card_Number\"	\"Exp_Month\"	\"Exp_Year\"	\"card_cid\"	\"NameOnCC\"	\"card_address\"	\"card_city\"	\"card_state\"	\"card_zip\"	\"readPolicy\"	\"submit1\"	\"Remote Name\"	\"Remote User\"	\"HTTP User Agent\"	\"Date\"	\"Time\"	\"Subtotal\"	\"Tax\"	\"BookingFee\"	\"CleaningFee\"	\"ImpactFee\"	\"Total\"\r\n\"%%first_name%%\"	\"%%last_name%%\"	\"%%email%%\"	\"%%phone_day%%\"	\"%%phone_eve%%\"	\"%%phone_fax%%\"	\"%%adults%%\"	\"%%kids%%\"	\"%%condo%%\"	\"%%arrive%%\"	\"%%depart%%\"	\"%%heard_from%%\"	\"%%instructions%%\"	\"%%cc_type%%\"	\"%%cc_num%%\"	\"%%cc_exp_month%%\"	\"%%cc_exp_year%%\"	\"%%cc_cvc%%\"	\"%%cc_name%%\"	\"%%address1%% %%address2%%\"	\"%%city%%\"	\"%%state%%\"	\"%%zip%%\"	\"%%agree_policies%%\"	\"submit\"	\"%%ip%%\"	\"%%ip%%\"	\"%%user_agent%%\"	\"%%now_date%%\"	\"%%now_time%%\"	\"%%subtotal%%\"	\"%%tax%%\"	\"%%booking%%\"	\"%%cleaning%%\"	\"%%impact%%\"	\"%%total%%\"'),
	(3,'Resort Copy','h','%%resort_name%% Reservation Request RC','<pre>first_name:      %%first_name%%\r\nlast_name:       %%last_name%%\r\nadults:          %%adults%%\r\nchildren:        %%kids%%\r\nCondo Type:      %%resort%% %%condo%%\r\nFirstArrive:     %%arrive%%\r\nFirstDepart:     %%depart%%\r\nDate:            %%now_date%%\r\nTime:            %%now_time%%\r\n\r\nComments:\r\n%%instructions%%</pre>'),
	(4,'Text Message','t','%%resort_name%% Reservation Request TXT','%%resort%%/%%condo%%/%%arrive%%/%%depart%%/%%last_name%%, %%first_name%%/%%adults%%,%%kids%%');
